# docker-compose.yml (example for development with volume)
version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    restart: always

    volumes:
      - .:/app # Mount your app code
      - /app/node_modules # Anonymous volume to prevent local node_modules from overwriting
      
volumes:
  node_modules: